export const synonyms = {
  "classificação": "classificacao",
  classificacao: "classificacao",
  alimentacao: "alimentação",
  transporte: "transportes",
  comercios: "comércios e serviços",
  "comercios e servicos": "comércios e serviços",
  "comercios e serviços": "comércios e serviços",
  "comércios e servicos": "comércios e serviços",
  "agências e operadores": "agencias e operadores",
  "estabelecimentos por municipio": "estabelecimentos_por_municipio",
  "estabelecimentos por município": "estabelecimentos_por_municipio",
  "funcionarios por municipio": "funcionarios_por_municipio",
  "funcionários por município": "funcionarios_por_municipio",
  "funcionarios ao longo do tempo": "funcionarios_ao_longo_do_tempo",
  "funcionários ao longo do tempo": "funcionarios_ao_longo_do_tempo",
  "saldo de funcionarios ao longo do tempo": "saldo_funcionarios_ao_longo_do_tempo",
  "saldo de funcionários ao longo do tempo": "saldo_funcionarios_ao_longo_do_tempo",
} as const;
